### ISSUE TITLE
Clean up try catch blocks

### ISSUE THREAD

**Issue by davidvorona** [Brethren-Studios/chimsockets#250]
Not sure why I did this originally but errors that are caught in a `try...catch...` block should just be logged, not thrown again.

UPDATE: I used `try...catch...` a little too liberally, and these should be severely culled across our server code.

**Comment by evanw555** [comment]
Actually, passing them up may be necessary if allowing the calling function to continue processing may mess up the business logic on the server. So in some cases, we should pass the error up, or maybe just only catch it at the higher level.

**Comment by rickfoop** [comment]
If we're not doing anything but logging the exception, I don't think its even worth catching the exception and then rethrowing. 

If we anticipate that an exception should be handled at a higher level, then just let the higher level log it and handle it properly. Otherwise we could easily log an exception twice or forget to rethrow and supress exceptions.
